# Bundled application configuration loaded when environment variables are absent.
# Update the values for your deployment or override them with environment variables.

admin_token: change-me

default_provider_name: openrouter
openrouter_key: "12312eqwe652"
openrouter_base_url: https://openrouter.ai/api/v1
openrouter_default_model: openrouter/auto

# Optional OpenAI provider configuration
openai_api_key: null

# Optional MCP agent configuration
mcp_agent_config: null
mcp_agent_servers: []
mcp_agent_app_name: chat-backend
mcp_agent_instruction: null
mcp_agent_llm_provider: openrouter
mcp_agent_default_model: null

# Redis and rate limiting
redis_url: redis://localhost:6379/0
rate_rps: 2
rate_burst: 5

# Session memory controls
memory_default: 10
memory_max: 50

# Observability and timeouts
metrics_enabled: true
log_level: INFO
provider_timeout_seconds: 30
