services:
  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - ../.env
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  mcp-ham3d:
    build:
      context: ..
      dockerfile: docker/ham3d.Dockerfile
    profiles: ["mcp"]
    env_file:
      - ../.env
    stdin_open: true
    tty: true
volumes:
  redis-data:
